# Generated by Django 5.0.3 on 2024-03-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
    ]
